enable-rpc=true
rpc-listen-all=true
rpc-listen-port=6800
rpc-max-request-size=1024M
max-concurrent-downloads=1000
max-connection-per-server=16
split=16
min-split-size=32M
optimize-concurrent-downloads=true
continue=true
auto-file-renaming=true
force-save=false
content-disposition-default-utf8=true
user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
http-accept-gzip=true
max-tries=20
check-certificate=false
bt-enable-lpd=true
bt-detach-seed-only=true
bt-remove-unselected-file=true
bt-max-peers=0
bt-max-open-files=1000
bt-request-peer-speed-limit=1M
seed-ratio=0
peer-id-prefix=-qB5210-
peer-agent=qBittorrent/5.2.1
follow-torrent=mem
enable-dht=true
enable-peer-exchange=true
listen-port=6881-6999
dht-listen-port=6881-6999
file-allocation=falloc
disk-cache=64M
check-integrity=true
max-upload-limit=1K
quiet=true
summary-interval=0
save-session=
save-session-interval=0
